name = "stores-platform"
main = "worker/index.js"
compatibility_date = "2025-12-01"
account_id = "0649c741a1ecb087ea2d37002e0517d5"

[[d1_databases]]
binding = "stores_db"       # This is the variable your Worker will use
database_name = "stores-db" # The name you gave in the dashboard
database_id = "7cc5336b-0276-4a75-b9e0-0b05a0f418d5"  # The ID from the dashboard

